// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "github.com/andhikagama/lmnlo/models/entity"
import filter "github.com/andhikagama/lmnlo/models/filter"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: f
func (_m *Repository) Fetch(f *filter.User) ([]*entity.User, error) {
	ret := _m.Called(f)

	var r0 []*entity.User
	if rf, ok := ret.Get(0).(func(*filter.User) []*entity.User); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*filter.User) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0
func (_m *Repository) Store(_a0 *entity.User) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
