// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import entity "github.com/andhikagama/lmnlo/models/entity"
import mock "github.com/stretchr/testify/mock"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Register provides a mock function with given fields: g
func (_m *Usecase) Register(g *entity.User) error {
	ret := _m.Called(g)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.User) error); ok {
		r0 = rf(g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
